Make PlantUML server base address configurable
adrianvlupu/C4-Builder pull request #25
Opened 2020-10-04 16:07 UTC by jikuja

* Fixes #15

2020-10-05 15:03 UTC, sju66 requested changes

2020-10-05 15:03 UTC, sju66 commented on cli.collect.js
> +        conf.set('serverBaseAddress', responses.serverBaseAddress);
Just change serverBaseAddress by plantUmlServerBaseAddress in order to be more understandable in the c4Builder file

2020-10-05 15:03 UTC, sju66 commented on cli.list.js
> +Server base address: ${currentConfiguration.SERVER_BASE_ADDRESS !== undefined ? chalk.green(currentConfiguration.SERVER_BASE_ADDRESS) : chalk.red('not set')}
"Server base address" => "PlantUml server base address" ?

2021-01-09 17:45 UTC, adrianvlupu commented
Thanks for this. I've merged a version containing both the plantuml server url and the image format. Should have probably merged this first.

2021-01-09 17:45 UTC, closed without merging

2021-01-09 17:46 UTC, adrianvlupu commented
Fixed by https://github.com/adrianvlupu/C4-Builder/pull/29